apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outreach

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - workers-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: outreach
  app.kubernetes.io/managed-by: kustomize
